meta_product_name: "Daily Live"
meta_title: "Daily Live, le programme de vos rendez-vous lives, talks, workshops, ateliers, DIY !"
meta_description: "Retrouvez tous les jours suivant vos disponibilités, vos rendez-vous en direct sur Instagram, Facebook, YouTube, Zoom etc...

Tous les meilleurs rendez-vous sont au programme !

Pour ne rater aucun rendez-vous, n’oubliez pas à vous abonner à notre compte Instagram @daily.live"
meta_image: "" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
